"""empty message

Revision ID: 1542b9fda304
Revises: f7a0621f4a30
Create Date: 2020-08-27 17:03:16.985953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1542b9fda304'
down_revision = 'f7a0621f4a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'versionsrole', ['version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'version_id')
    # ### end Alembic commands ###
