"""empty message

Revision ID: 5ec78bd04528
Revises: 
Create Date: 2020-08-27 16:35:57.295250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec78bd04528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versionsrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions_rules',
    sa.Column('versionsrole_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['versionsrole_id'], ['versionsrole.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions_rules')
    op.drop_table('versionsrole')
    # ### end Alembic commands ###
