"""empty message

Revision ID: f7a0621f4a30
Revises: 5ec78bd04528
Create Date: 2020-08-27 16:46:30.154560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a0621f4a30'
down_revision = '5ec78bd04528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions_roles',
    sa.Column('versionsrole_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['versionsrole_id'], ['versionsrole.id'], )
    )
    op.drop_table('versions_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions_rules',
    sa.Column('versionsrole_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['versionsrole_id'], ['versionsrole.id'], )
    )
    op.drop_table('versions_roles')
    # ### end Alembic commands ###
